const { chromium } = require('playwright')
const fs = require("fs");
const path = require('path');
const https = require("https")
const email = "alexdrobinka@gmail.com"
const password = "NKkkNan31K!";

async function getCookies() {
    // const browser = await chromium.launch({headless: false, args: ["--disable-blink-features=AutomationControlled"]});
    const browser = await chromium.launch({headless: true, args: ["--disable-blink-features=AutomationControlled"]});
    const context = await browser.newContext();
    const page = await context.newPage();
    page.on("requestfinished", async request => {
        const headers = await request.allHeaders()
        if(headers.host != "api.boosty.to" || !headers.cookie.includes("accessToken")) return
        var cookie = headers.cookie
        var auth = cookie.substring(cookie.indexOf("auth=") + 5, cookie.lastIndexOf('"redirectAppId":"web"}') + 22)
        fs.writeFileSync(path.join(__dirname, "boostyCookies.txt"), JSON.stringify(auth), "utf-8")
        fs.writeFileSync("/Users/jmail/boosty.to_cookies.txt", `# Netscape HTTP Cookie File\n# This file is generated by yt-dlp.  Do not edit.\n\n.boosty.to	TRUE	/	TRUE	1688982161	auth	${auth.toString()}`, "utf-8")
        await browser.close()
    })
    await googleAuth(page).catch(err => console.log(err))
    await page.waitForTimeout(3000)
    await boostyAuth(page).catch(err => console.log(err))
    await page.waitForTimeout(3000)
}

async function googleAuth(page) {
    await page.goto("https://accounts.google.com/signin/v2/identifier?hl=en&flowName=GlifWebSignIn&flowEntry=ServiceLogin");
    await page.waitForSelector('input[type="email"]');
    await page.type('input[type="email"]', email);
    await page.click("#identifierNext");
    await page.waitForSelector('input[type="password"]', { visible: true });
    await page.type('input[type="password"]', password);
    await page.waitForSelector("#passwordNext", { visible: true });
    await page.click("#passwordNext");
    await page.waitForLoadState("load", {timeout: 4000})
}

async function boostyAuth(page) {
    await page.goto("https://boosty.to")
    await page.waitForSelector("#topMenu > div.TopMenu_right_yjO9f > div > button.BaseButton_button_yO8r5.ContainedButton_button_mJG1l.ContainedButton_colorDefault_fJta6")
    await page.click("#topMenu > div.TopMenu_right_yjO9f > div > button.BaseButton_button_yO8r5.ContainedButton_button_mJG1l.ContainedButton_colorDefault_fJta6")
    await page.waitForSelector("#root > div > div.ScrollBox_scrollContainer_g0g0j.Popup_wrapper_ZeN1U.FadeIn_fade_ecikC.FadeIn_entered_uFjQ8.ScrollBox_scrollContainerFixedHeight_Sxrzx > div > div > div.PopupContent_content_A2EA3.AuthSignInPopup_popupContent_CoVO3 > div > div.Authorization_providers_ZohCR > div:nth-child(4)")
    await page.click("#root > div > div.ScrollBox_scrollContainer_g0g0j.Popup_wrapper_ZeN1U.FadeIn_fade_ecikC.FadeIn_entered_uFjQ8.ScrollBox_scrollContainerFixedHeight_Sxrzx > div > div > div.PopupContent_content_A2EA3.AuthSignInPopup_popupContent_CoVO3 > div > div.Authorization_providers_ZohCR > div:nth-child(4)")
    await page.waitForLoadState("load", {timeout: 10000})
}

module.exports = { getCookies }